os:
  users:
  - name: test
    password: testpassword
    primaryGroup: sudo
  additionalFiles:
    artifacts/90azl-livenet/liveos-artifacts-download.service:
      - path: /etc/systemd/system/liveos-artifacts-download.service
        permission: "644"
    artifacts/90azl-livenet/liveos-artifacts-download.sh:
      - path: /usr/lib/dracut/modules.d/90azl-livenet/liveos-artifacts-download.sh
        permission: "755"
    artifacts/90azl-livenet/schedule-liveos-artifacts-download.sh:
      - path: /usr/lib/dracut/modules.d/90azl-livenet/schedule-liveos-artifacts-download.sh
        permission: "755"
    artifacts/90azl-livenet/azl-livenet-genrules.sh:
      - path: /usr/lib/dracut/modules.d/90azl-livenet/azl-livenet-genrules.sh
        permission: "755"
    artifacts/90azl-livenet/module-setup.sh:
      - path: /usr/lib/dracut/modules.d/90azl-livenet/module-setup.sh
        permission: "755"
    artifacts/liveos-dracut-pxe.conf:
      - path: /etc/dracut.conf.d/10-liveos-dracut-pxe.conf
        permission: "644"
