iso:
  kernelCommandLine:
    extraCommandLine: "url=http://1.2.3.4"
os:
  users:
  - name: test
    password: testpassword
    primaryGroup: sudo
  additionalFiles:
    dracut-downloader-module/download-artifacts.sh: /usr/lib/dracut/modules.d/90micdownloader/download-artifacts.sh
    dracut-downloader-module/module-setup.sh: /usr/lib/dracut/modules.d/90micdownloader/module-setup.sh
    dracut-downloader-module/dracut-include-mic-downloader.conf: /etc/dracut.conf.d/90-dracut-include-mic-downloader.conf
